version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_farmacia
    environment:
      POSTGRES_USER: laura
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: farmacia
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laura -d farmacia"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  liquibase:
    image: liquibase/liquibase:4.27
    container_name: liquibase_farmacia
    volumes:
      - .:/liquibase/changelog
      - ./lib:/liquibase/lib
    depends_on:
      db:
        condition: service_healthy
    command: >
      --searchPath=/liquibase/changelog
      --changelog-file=db.changelog.xml
      --url=jdbc:postgresql://db:5432/farmacia
      --username=laura
      --password=12345
      --classpath=/liquibase/lib/postgresql-42.7.10.jar
      update
